---
# tasks file for gitrepo    
- name: Create steamcmd directory
  file:
    path: /home/steam/steamcmd
    state: directory
    mode: '0755'
    owner: steam
  become_user: steam
- name: Download steamcmd
  shell: cd /home/steam && sudo wget http://media.steampowered.com/installer/steamcmd_linux.tar.gz
- name: Give steam permissions to steamcmd folder
  file:
    path: /home/steam/steamcmd
    owner: steam
    recurse: yes
    state: directory
- name: extract steamcmd
  shell: cd /home/steam && tar -xvzf steamcmd_linux.tar.gz
  args:
    executable: /bin/bash
  become_user: steam
- name: Install Valheim
  shell: cd /home/steam && ./steamcmd.sh +login anonymous +force_install_dir /home/steam/steamcmd +app_update 896660 validate +exit    
  args:
    executable: /bin/bash
  become_user: steam  
- name: Move start server script.
  copy: 
    src: ../files/start_server.sh
    dest: /home/steam/steamcmd/start_server.sh
    owner: steam
- name: Filewall enable port 22 tcp
  firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
- name: firewall enable port 2456-2458 tcp
  firewalld:
    port: 2456-2458/tcp
    permanent: true
    state: enabled
- name: firewall enable port 2456-2458 udp
  firewalld:
    port: 2456-2458/udp
    permanent: true
    state: enabled
- name: start and enable firewalld
  systemd:
    name: firewalld
    state: started
    daemon_reload: yes
    enabled: yes
- name: Run Valheim server.
  shell: cd /home/steam/steamcmd && ./start_server.sh
  become_user: steam
- name: Get running process of Server
  shell: "ps aux | grep server | cut -c 12-17 | head -n 1"
  register: server_process
- name: Wait 15 seconds
  pause:
    prompt: Waiting 15 seconds for server to start.
    seconds: 15
- name: Kill running processes
  shell: "kill -15 {{ item }}"
  with_items: "{{ server_process.stdout_lines }}"
- name: Extract world folder
  unarchive:
    src: ../../../worldbackup/worlds.zip
    dest: /home/steam/.config/unity3d/IronGate/Valheim
    owner: steam
    group: steam
- name: Run Valheim server.
  shell: cd /home/steam/steamcmd && ./start_server.sh
  become_user: steam
...
