---
# tasks file for gitrepo    
- name: Create steamcmd directory
  file:
    path: /home/steam/steamcmd
    state: directory
    mode: '0755'
    owner: steam
  become_user: steam
- name: Download steamcmd
  get_url:
    url: "http://media.steampowered.com/installer/steamcmd_linux.tar.gz"
    dest: /home/steam/steamcmd_linux.tar.gz
- name: Give steam permissions to steamcmd folder
  file:
    path: /home/steam/steamcmd
    owner: steam
    recurse: yes
    state: directory
- name: Extract steamcmd
  unarchive:
    src: /home/steam/steamcmd_linux.tar.gz
    dest: /home/steam/
    owner: steam
    group: steam
    remote_src: yes
- name: Install Valheim
  shell: cd /home/steam && ./steamcmd.sh +login anonymous +force_install_dir /home/steam/steamcmd +app_update 896660 validate +exit    
  args:
    executable: /bin/bash
  become_user: steam  
- name: Move start server script.
  copy: 
    src: ../files/start_server.sh
    dest: /home/steam/steamcmd/start_server.sh
    owner: steam
    group: steam
- name: Filewall enable port 22 tcp
  firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
- name: firewall enable port 2456-2458 tcp
  firewalld:
    port: 2456-2458/tcp
    permanent: true
    state: enabled
- name: firewall enable port 2456-2458 udp
  firewalld:
    port: 2456-2458/udp
    permanent: true
    state: enabled
- name: start and enable firewalld
  systemd:
    name: firewalld
    state: started
    daemon_reload: yes
    enabled: yes
- name: Run Valheim server.
  shell: cd /home/steam/steamcmd && ./start_server.sh
  become_user: steam
...
